name: somatic-variant-calling
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.7
  - pandas
  - bumpversion
  - snakemake-minimal
  - git-lfs
  - seaborn
  - torch
  - numpy
